---
name: Deploy Logic App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      LOGIC_APP_NAME: 'logic-app-preview-la'
      STORAGE_ACCOUNT_NAME: 'logicapppreviewsto'
      ASP_NAME: 'logic-app-preview-asp'
      INSIGHTS_NAME: 'logic-app-preview-ins'
      LOCATION: 'northeurope'
      RESOURCE_GROUP: 'Logic-App'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: logic-app-package
          path: logic-app-package

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Infrastructure
        uses: Azure/arm-deploy@v1

        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: infrastructure/arm-template.json
          deploymentMode: Incremental
          parameters: logicAppName=${{ env.LOGIC_APP_NAME }} storageAccountName=${{ env.STORAGE_ACCOUNT_NAME }} appServicePlanName=${{ env.ASP_NAME }} insightsName=${{ env.INSIGHTS_NAME }} location=${{ env.LOCATION }}

      - name: Deploy Logic App
        uses: Azure/functions-action@v1.3.1
        with:
          app-name: ${{ env.LOGIC_APP_NAME }}
          package: logic-app-package
